In [23]:
import librosa 
from demucs.api import Separator
import torchaudio 
import torch

from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq
import soundfile as sf

In [7]:
SEPARADOR = Separator (model = "htdemucs")

In [ ]:
WAV, SR = librosa.load (r"C:\Users\Admin\Desktop\ip\Automatic Speech Recognition\audio\audio8.wav", sr = 44100, mono = False) #44100 porque é o que o Demucs precisa de receber

display (WAV)
print (WAV.shape) 
print (type (WAV)) #<class 'numpy.ndarray'>

WAV = torch.from_numpy (WAV)

display (WAV)
print (WAV.shape) 
print (type (WAV))
print (WAV.dtype)

ORIGINAL, SEPARADO = SEPARADOR.separate_tensor (WAV, sr = SR)

print (SEPARADO.keys())

VOZES = SEPARADO ["vocals"]

VOZES = torchaudio.functional.resample (VOZES, orig_freq = SR, new_freq = 16000)
VOZES = VOZES.mean (dim = 0)

display (VOZES)
print (VOZES.shape) 
print (type (VOZES))
print (VOZES.dtype)

sf.write ("x.wav", VOZES, samplerate = 16000)

array([[ 0.00772119,  0.00207531, -0.00680542, ...,  0.397534  ,
         0.3835261 ,  0.32648695],
       [ 0.00772119,  0.00207531, -0.00680542, ...,  0.397534  ,
         0.3835261 ,  0.32648695]], shape=(2, 2389216), dtype=float32)

(2, 2389216)
<class 'numpy.ndarray'>


tensor([[ 0.0077,  0.0021, -0.0068,  ...,  0.3975,  0.3835,  0.3265],
        [ 0.0077,  0.0021, -0.0068,  ...,  0.3975,  0.3835,  0.3265]])

torch.Size([2, 2389216])
<class 'torch.Tensor'>
torch.float32
dict_keys(['drums', 'bass', 'other', 'vocals'])


tensor([ 0.0039, -0.0058, -0.0204,  ...,  0.0481,  0.3318,  0.3606])

torch.Size([866836])
<class 'torch.Tensor'>
torch.float32


In [14]:
device = "cuda" if torch.cuda.is_available () else "cpu"

PROCESSOR = AutoProcessor.from_pretrained (r"C:\Users\Admin\Desktop\models\ASR Models\Whisper\WhisperLv3-PT-All 4Bit")
MODEL_ASR = AutoModelForSpeechSeq2Seq.from_pretrained (r"C:\Users\Admin\Desktop\models\ASR Models\Whisper\WhisperLv3-PT-All 4Bit", device_map = device, dtype = torch.float16)

W0907 10:01:38.650000 8232 Lib\site-packages\torch\utils\flop_counter.py:29] triton not found; flop counting will not work for triton kernels
Loading weights: 100%|██████████| 1259/1259 [00:03<00:00, 341.29it/s]


In [35]:
inputs = PROCESSOR (VOZES, sampling_rate = PROCESSOR.feature_extractor.sampling_rate, return_tensors = "pt", truncation = False) # Truncation obrigatório para áudios >30s
inputs = inputs["input_features"].to (device, dtype = torch.float16) # Passar para GPU

with torch.inference_mode ():
    outputs = MODEL_ASR.generate (inputs, return_timestamps = True, task = "transcribe", language = "pt", num_beams = 5) # Beam Search # return_timestamps obrigatório para áudios >30s 

trans = PROCESSOR.batch_decode (outputs, skip_special_tokens = True)[0]

In [36]:
print (trans)

boa tarde peço desculpa incomodála é o seguinte nós estamos a ligar por causa da da conta da água a conta da água que se encontra ainda por liquidarsim mas eu agora estou aqui em baixo e venho aqui a ocasião e quem trata disso é sempre a minha mulher ela é que trata dessas coisas e agora não tem aqui mas mas isto está farto ela ela paga logo vem cá tirar a conta da água e ela paga tirar a conta ah não não espera aí está está a confundir portanto o senhor está a falar da conta da água da rede pública certoestá bem mas essa essa água da chuva tem dono então mas quem é que você acha que lhe mandou para aí a chuva então porque nós não porque é uma é uma portaria recente chove em todo o lado porque a gente manda para todo o lado


<hr>

In [39]:
ORI, SR2 = librosa.load (r"C:\Users\Admin\Desktop\ip\Automatic Speech Recognition\audio\audio8.wav", sr = 16000, mono = True)

In [40]:
inputs_normal = PROCESSOR (ORI, sampling_rate = PROCESSOR.feature_extractor.sampling_rate, return_tensors = "pt", truncation = False)
inputs2 = inputs_normal["input_features"].to (device, dtype = torch.float16)

with torch.inference_mode ():
    outputs2 = MODEL_ASR.generate (inputs2, return_timestamps = True, task = "transcribe", language = "pt", num_beams = 5) # Beam Search # return_timestamps obrigatório para áudios >30s 

trans2 = PROCESSOR.batch_decode (outputs2, skip_special_tokens = True)[0]

In [41]:
print (trans2)

boa tarde peço desculpa incomodála é o seguinte nós estamos a ligar por causa da da conta da água a conta da água que se encontra ainda por liquidarsim mas eu agora estou aqui em baixo e venho aqui a ocasião e quem trata disso é sempre a minha mulher ela é que trata dessas coisas e agora não tem aqui mas mas isto está farto ela ela paga logo vem cá tirar a conta da água e ela paga tirar a conta ah não não espera aí está está a confundir portanto o senhor está a falar da conta da água da rede pública certoestá bem mas essa essa água da chuva tem dono então mas quem é que você acha que lhe mandou para aí a chuva então porque nós não porque é uma é uma portaria recente chove em todo o lado porque a gente manda para todo o lado


In [1]:
from demucs.api import Separator

separator = Separator(model = "htdemucs")

origin, separated = separator.separate_audio_file(r"C:\Users\Admin\Desktop\audio files\2_background noise.wav")

print(separated.keys())

c:\Users\Admin\Desktop\ip\Automatic Speech Recognition\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


dict_keys(['drums', 'bass', 'other', 'vocals'])


In [3]:
print (separated["vocals"])
print (separated["vocals"].shape)
print (type(separated["vocals"]))

tensor([[ 6.5849e-06, -5.3038e-06,  1.1738e-05,  ..., -2.2224e-06,
          6.4668e-06, -1.7344e-06],
        [-2.4067e-05, -6.5974e-05, -1.1788e-05,  ..., -1.6006e-06,
          6.5405e-06, -1.3293e-06]])
torch.Size([2, 1803690])
<class 'torch.Tensor'>


In [ ]:
import librosa

WAV, SR = librosa.load (r"C:\Users\Admin\Desktop\audio files\2_background noise.wav", sr = 44100, mono = False)

print (WAV)
print (WAV.shape)
print (type(WAV)) #<class 'numpy.ndarray'>

[6.0977236e-05 7.2154056e-05 6.1054569e-05 ... 0.0000000e+00 0.0000000e+00
 0.0000000e+00]
(654400,)
<class 'numpy.ndarray'>


In [ ]:
NORMAL, SEPARADO = separator.separate_tensor (WAV)

In [5]:
import torch

In [ ]:
TESTE = torch.from_numpy (WAV)
print (TESTE)
print (TESTE.shape)
print (type (TESTE))



tensor([6.0977e-05, 7.2154e-05, 6.1055e-05,  ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00])
torch.Size([654400])
<class 'torch.Tensor'>


RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [ ]:
print (separated["vocals"])

import soundfile as sf

sf.write ("asxas.wav", separated["vocals"], 16000)

In [ ]:
import numpy, torchaudio

origin, separated = separator.separate_audio_file(r"C:\Users\Admin\Desktop\audio files\2_background noise.wav")

vocals = separated["vocals"].cpu()

vocals = separated["vocals"]

gain_db = 3
gain = 10 ** (gain_db / 20)

vocals = vocals * gain


vocals = torchaudio.functional.resample(
    vocals,
    separator.samplerate,
    16000
)

sf.write(
    "speech.wav",
    vocals.numpy().T,
    16000
)

In [ ]:
from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq
import torch

device = "cuda" if torch.cuda.is_available () else "cpu"

PROCESSOR = AutoProcessor.from_pretrained (r"C:\Users\Admin\Desktop\models\ASR Models\Whisper\WhisperLv3-PT-All 4Bit")
MODELO = AutoModelForSpeechSeq2Seq.from_pretrained (r"C:\Users\Admin\Desktop\models\ASR Models\Whisper\WhisperLv3-PT-All 4Bit", device_map = device, dtype = torch.float16)

In [ ]:
import librosa

WAV, SAMPLE_RATE = librosa.load (r"C:\Users\Admin\Desktop\ip\Automatic Speech Recognition\code\speech.wav", sr = 16000, mono = True)

inputs = PROCESSOR (WAV, return_tensors = "pt", sampling_rate = 16000, truncation = False)
inputs = inputs["input_features"].to (device, dtype = torch.float16)

with torch.inference_mode ():
    output = MODELO.generate (inputs, return_timestamps = True, task = "transcribe", language = "pt", num_beams = 5)

print (PROCESSOR.batch_decode (output, skip_special_tokens = True)[0]) 