In [1]:
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor

from transformers.audio_utils import load_audio

import torch

import time


In [2]:
device = "cuda" if torch.cuda.is_available () else "cpu"

In [3]:
MODEL = r"C:\Users\Admin\Desktop\models\ASR Models\Whisper\WhisperLv3-PT-All 8Bit"

PROCESSOR_ASR = AutoProcessor.from_pretrained (MODEL)
MODEL_ASR = AutoModelForSpeechSeq2Seq.from_pretrained (MODEL, device_map = device, dtype = torch.float16)

W0807 16:34:00.762000 6292 Lib\site-packages\torch\utils\flop_counter.py:29] triton not found; flop counting will not work for triton kernels
Loading weights: 100%|██████████| 1259/1259 [00:01<00:00, 699.00it/s]


In [4]:
WAV = load_audio (r"C:\Users\Admin\Desktop\ip\Automatic Speech Recognition\audio\audio4.wav", sampling_rate = PROCESSOR_ASR.feature_extractor.sampling_rate)

In [5]:
inputs = PROCESSOR_ASR (WAV, sampling_rate = PROCESSOR_ASR.feature_extractor.sampling_rate, return_tensors = "pt", truncation = False).to(device) #TRUNCATION OBRIGATÓRIO PARA ÁUDIOS > 30s

print (inputs)
print (inputs["input_features"])
print (inputs["input_features"].shape)

{'input_features': tensor([[[ 0.1687,  0.4199,  0.3027,  ..., -0.1936, -0.3392, -0.2835],
         [ 0.2663,  0.5175,  0.4002,  ..., -0.0960, -0.2416, -0.1860],
         [ 0.4315,  0.6749,  0.6387,  ..., -0.3736,  0.0260,  0.0459],
         ...,
         [-0.1668, -0.1455, -0.1311,  ..., -0.2738, -0.3031, -0.1841],
         [-0.2993, -0.2134, -0.2334,  ..., -0.3732, -0.2663, -0.0453],
         [-0.4550, -0.4550, -0.4550,  ..., -0.4550, -0.4550, -0.1880]]],
       device='cuda:0')}
tensor([[[ 0.1687,  0.4199,  0.3027,  ..., -0.1936, -0.3392, -0.2835],
         [ 0.2663,  0.5175,  0.4002,  ..., -0.0960, -0.2416, -0.1860],
         [ 0.4315,  0.6749,  0.6387,  ..., -0.3736,  0.0260,  0.0459],
         ...,
         [-0.1668, -0.1455, -0.1311,  ..., -0.2738, -0.3031, -0.1841],
         [-0.2993, -0.2134, -0.2334,  ..., -0.3732, -0.2663, -0.0453],
         [-0.4550, -0.4550, -0.4550,  ..., -0.4550, -0.4550, -0.1880]]],
       device='cuda:0')
torch.Size([1, 128, 5417])


In [ ]:
ids = MODEL_ASR.generate (inputs["input_features"], return_timestamps = True, task = "transcribe", language = "pt", return_segments = True)

In [52]:
#print (ids.keys())
#print (ids["sequences"])
#print (ids["segments"])

for x in ids["segments"][0]:
    print (x["tokens"])
    print (PROCESSOR_ASR.decode (x["tokens"]))
    #print (PROCESSOR_ASR.decode (x["tokens"]))


tensor([50365,  1763,    64, 27367,   520,  8560,   730,  2444,  4306, 14036,
          378,   842,   635,  1136,   277, 32433,  9738, 10382,   257, 11742,
          289,  1515, 23667,  1120,  1120, 24001,  1120, 23824,   257, 24001,
         1120, 23824,   631,   369, 43621, 11804,  1515,  6553,   289, 50988,
        50988], device='cuda:0')
boa tarde peço desculpa incomodá la é o seguinte nós estamos a ligar por causa da da conta da água a conta da água que se encontra ainda por liquidar
tensor([50365,  2259,   271,  2300,  2228,  9851, 17660,  3871,   846, 30934,
          308,  6138,  1289,  3871,  8130,  3058,  1076,   308, 13026, 31920,
        20088,  1136,  9553,   257, 11720, 33211,  7175,  1136,   631, 31920,
        40083, 14567,   308,  9851,  2431,  1383,  3871,  2300,  2300,  4616,
         3192, 17474,  7175,  7175,   280,  9286,  9699, 19053,  6476, 29239,
          257, 24001,  7461,   308,  7175,   280,  9286, 50886, 51094],
       device='cuda:0')
pois mas eu agora e